dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "nightly"

install:
  - travis_retry pip install bandit coverage

script:
  - bandit -ll -r asyncmock
  - python setup.py test
